export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const GET_EPISODE_REQUEST = 'GET_EPISODE_REQUEST';
export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS';
export const GET_EPISODE_FAILURE = 'GET_EPISODE_FAILURE';

export const GET_CHARACTER_REQUEST = 'GET_CHARACTER_REQUEST';
export const GET_CHARACTER_SUCCESS = 'GET_CHARACTER_SUCCESS';
export const GET_CHARACTER_FAILURE = 'GET_CHARACTER_FAILURE';
